#[cfg(any(feature = "enable-rofi-c-shared", feature = "enable-ucx"))]
use std::env;
#[cfg(any(feature = "enable-rofi-c-shared", feature = "enable-ucx"))]
use std::path::PathBuf;
use std::fs::File;
use std::io::Write;

fn main() {
    let mut lib_paths: Vec<String> = Vec::new();
    
    println!("cargo:rerun-if-env-changed=DEP_ROFI_ROOT");
    #[cfg(feature = "enable-rofi-c-shared")]
    {
        if let Ok(rofi_lib_dir) = env::var("DEP_ROFI_ROOT") {
            let lib_path = PathBuf::from(rofi_lib_dir).join("lib");
            println!("cargo:rustc-link-search=native={}", lib_path.display());
            println!("cargo:rustc-link-arg=-Wl,-rpath,{}", lib_path.display());
            lib_paths.push(lib_path.display().to_string());
        } else {
            panic!(
                "unable to set rofi backend, recompile with 'enable-rofi' feature {:?}",
                env::vars()
            )
        }
    }
    println!("cargo:rerun-if-env-changed=DEP_UCX_ROOT");
    #[cfg(feature = "enable-ucx")]
    {
        if let Ok(lamellar_ucx_lib_dir) = env::var("DEP_UCX_ROOT") {
            let lib_path = PathBuf::from(lamellar_ucx_lib_dir).join("lib");
            println!("cargo:rustc-link-search=native={}", lib_path.display());
            println!("cargo:rustc-link-arg=-Wl,-rpath,{}", lib_path.display());
            lib_paths.push(lib_path.display().to_string());
        } else {
            panic!(
                "unable to set lamellar-ucx backend, recompile with 'enable-ucx' feature {:?}",
                env::vars()
            )
        }
    }

    println!("cargo:rerun-if-env-changed=DEP_PMINATIVE_ROOT");
    if let Ok(pmi_native_lib_dir) = env::var("DEP_PMINATIVE_ROOT") {
        let lib_path = PathBuf::from(pmi_native_lib_dir).join("lib");
        println!("cargo:rustc-link-search=native={}", lib_path.display());
        println!("cargo:rustc-link-arg=-Wl,-rpath,{}", lib_path.display());
        lib_paths.push(lib_path.display().to_string());
    } else {
        panic!(
            "unable to set pmi backend, recompile with 'pmi' feature {:?}",
            env::vars()
        )
    }
    println!("cargo:warning={:?}", env::vars());
    
    // Generate bash script with library paths
    // Navigate from OUT_DIR to the workspace root (where cargo was invoked)
    let out_dir = env::var("OUT_DIR").unwrap_or_else(|_| ".".to_string());
    let out_path = PathBuf::from(out_dir);
    
    // OUT_DIR is typically target/debug/build/<crate>/out
    // Navigate up to find the project root (where target/ is)
    let mut script_dir = out_path.clone();
    while script_dir.file_name().is_some() {
        if script_dir.join("Cargo.toml").exists() || script_dir.join("target").exists() {
            break;
        }
        if !script_dir.pop() {
            // Fallback to current directory if we can't find project root
            script_dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
            break;
        }
    }
    
    let script_path = script_dir.join("lamellar_env.sh");
    
    if let Ok(mut file) = File::create(&script_path) {
        writeln!(file, "#!/bin/bash").ok();
        writeln!(file, "# Auto-generated by build.rs - DO NOT EDIT").ok();
        writeln!(file, "# Source this file before running lamellar applications").ok();
        writeln!(file, "# Usage: source lamellar_env.sh").ok();
        writeln!(file, "").ok();
        
        if !lib_paths.is_empty() {
            write!(file, "export LD_LIBRARY_PATH=").ok();
            for (i, path) in lib_paths.iter().enumerate() {
                if i > 0 {
                    write!(file, ":").ok();
                }
                write!(file, "{}", path).ok();
            }
            writeln!(file, ":$LD_LIBRARY_PATH").ok();
        }
        
        println!("cargo:warning=Generated library path script: {}", script_path.display());
    }
    else {
        panic!("Failed to create lamellar_env.sh");
    }
    
   
    
}
